// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jomgiqbindbbeealyvbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvbWdpcWJpbmRiYmVlYWx5dmJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0ODA0MDYsImV4cCI6MjA2NjA1NjQwNn0.C-Z5Agg2De5_xXYSAnM4RJTt3Hb4zUHDHnchvTVDyb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);